{% set name = "pytng" %}
{% set version = "0.2.3" %}
{% set sha256 = "4601285d9fce9fe1b6b7e1d313ce3324799073edc91b2b09c8ffd78147ec52a8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }} 

build:
  skip: true  # [win and py2k]
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    
  host:
    - python
    - pip
    - cython
    - numpy
    - zlib

  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pytng

about:
  home: https://github.com/MDAnalysis/pytng
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A Python library to read TNG files'

  description: |
    PyTNG is a Python library to read TNG files.  The TNG format is used by
    molecular simulation packages such as GROMACS to enable efficient
    storage of trajectory data.

  doc_url: https://www.mdanalysis.org/pytng
  dev_url: https://github.com/MDAnalysis/pytng

extra:
  recipe-maintainers:
    - hmacdope
    - orbeckst
    - richardjgowers
